# Generated by Django 4.2.3 on 2023-07-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_listing_comments_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="comments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.comment",
            ),
        ),
    ]
