# Generated by Django 4.2.3 on 2023-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_listing_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.CharField(default="null", max_length=50),
        ),
    ]
