# Generated by Django 4.2.3 on 2023-07-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_listing_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="comments",
        ),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.listing",
            ),
        ),
    ]
