# Generated by Django 4.2.3 on 2023-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_remove_listing_comments_comment_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("N", "None"),
                    ("AN", "Animal"),
                    ("HS", "House"),
                    ("S", "Sport"),
                    ("HB", "Hobby"),
                    ("E", "Electronics"),
                    ("F", "Food"),
                    ("A", "Art"),
                    ("AM", "Automobile"),
                ],
                default="N",
                max_length=13,
            ),
        ),
    ]
