# Generated by Django 4.2.3 on 2023-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
